#!/usr/bin/env ruby
# -*- ruby -*-
require 'rubygems'
require 'daemon_spawn'

RAILS_ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))

multiplicity = 1

if ARGV[0] == '-n' && ARGV.size > 1
  multiplicity = ARGV[1].to_i
  ARGV.shift 2
end


class DelayedJobWorker < DaemonSpawn::Base
  def start(args)
    ENV['RAILS_ENV'] ||= args.first || 'development'
    Dir.chdir RAILS_ROOT
    require File.join('config', 'environment')

    Delayed::Worker.new.start
  end

  def stop
    system("kill `cat #{self.pid_file}`")
  end
end

multiplicity.times do |i|
  DelayedJobWorker.spawn!({:log_file => File.join(RAILS_ROOT, "log", "delayed_job.log"),
                          :pid_file => File.join(RAILS_ROOT, 'tmp', 'pids', "delayed_job_#{i}.pid"),
                          :sync_log => true,
                          :working_dir => RAILS_ROOT}, ARGV[0..0])
end

